COND = {'Blinded': 0,
        'Charmed': 0,
        'Deafened': 0,
        'Fatigued': 0,
        'Frightened': 0,
        'Grappled': 0,
        'Incapacitated': 0,
        'Invisible': 0,
        'Paralyzed': 0,
        'Petrified': 0,
        'Poisoned': 0,
        'Prone': 0,
        'Restrained': 0,
        'Stunned': 0,
        'Unconscious': 0,
        'Exhaustion': 0}
