SKILLS = {'acrobatics': {'stat': 'dex'},
          'animal handling': {'stat': 'wis'},
          'arcana': {'stat': 'int'},
          'athletics': {'stat': 'str'},
          'deception': {'stat': 'cha'},
          'history': {'stat': 'int'},
          'insight': {'stat': 'wis'},
          'intimidation': {'stat': 'cha'},
          'investigation': {'stat': 'int'},
          'medicine': {'stat': 'wis'},
          'nature': {'stat': 'int'},
          'perception': {'stat': 'wis'},
          'performance': {'stat': 'cha'},
          'persuasion': {'stat': 'cha'},
          'religion': {'stat': 'int'},
          'sleight of hand': {'stat': 'dex'},
          'stealth': {'stat': 'dex'},
          'survival': {'stat': 'wis'},
          }
