from typing import Any, Optional

from item.components import Component


def validate_input(func: Any): ...


class AC(Component):
    AC_KEYS: Any = ...

    def __init__(self, ac: dict = ...) -> None: ...

    def __getitem__(self, item: Any): ...

    def __setitem__(self, key: Any, value: Any) -> None: ...

    def get(self, key: Any, default: Optional[Any] = ...): ...

    def update(self, char_sheet: dict) -> Any: ...

    def update_ac(self) -> None: ...

    @property
    def ac(self): ...

    @ac.setter
    def ac(self, value: dict) -> Any: ...
