from typing import Any, Optional

from item.components import Component


class AC(Component):
    AC_KEYS: Any = ...

    def __init__(self, *, flat_ac: int = ..., dex_cap: int = ..., dex: int = ..., use_dex: bool = ...) -> None: ...

    def __getitem__(self, item: str) -> Any: ...

    def __setitem__(self, key: str, value: int) -> Any: ...

    def get(self, key: Any, default: Optional[Any] = ...): ...

    def update(self, char_sheet: dict) -> Any: ...

    def update_ac(self) -> None: ...

    @property
    def ac(self): ...

    @ac.setter
    def ac(self, **kwargs: Any) -> None: ...
