from typing import Any, Union

from item.components import Component


class Volume(int):
    def __init__(self, value: int = ...) -> None: ...

    def __add__(self, other: Any): ...

    def __sub__(self, other: Any): ...

    @property
    def value(self): ...

    @value.setter
    def value(self, val: Any) -> None: ...

    def to_imperial(self) -> None: ...

    def to_metric(self) -> None: ...


class CubicFeet(Volume):
    def __init__(self, value: int = ...) -> None: ...

    def to_metric(self): ...


class CubicMeter(Volume):
    def __init__(self, value: int = ...) -> None: ...

    def to_imperial(self): ...


class Capacity(Component):
    def __init__(self, capacity: Union[CubicMeter, CubicFeet, int] = ...) -> None: ...

    @property
    def capacity(self): ...

    @capacity.setter
    def capacity(self, capacity: Any) -> None: ...

    def update(self, char_sheet: dict) -> Any: ...
