from typing import Any

from components import Component


class Charges(Component):
    def __init__(self, init_charge: int = ...) -> None: ...

    def __add__(self, other: int) -> Any: ...

    def __sub__(self, other: int) -> Any: ...

    @property
    def charges(self): ...

    @charges.setter
    def charges(self, charges: Any) -> None: ...

    def update(self, char_sheet: Character) -> Any: ...
