from typing import Any

from enums import COIN
from . import Component as Component


class CoinDict(dict):
    coin_names: Any = ...

    def __init__(self, **kwargs: Any) -> None: ...

    def __getitem__(self, item: COIN) -> Any: ...

    def __setitem__(self, key: COIN, value: int) -> Any: ...


class Cost(Component):
    def __init__(self, cost: CoinDict = ...) -> None: ...

    def __eq__(self, other: Any) -> Any: ...

    def __lt__(self, other: Any) -> Any: ...

    @property
    def cost(self): ...

    def update(self, char_sheet: dict) -> Any: ...
