from typing import Any

from utils.enums import COIN
from . import Component as Component


class Cost(Component):
    kwcoins: Any = ...

    def __init__(self, **kwargs: Any) -> None: ...

    def __eq__(self, other: Any) -> Any: ...

    def __lt__(self, other: Any) -> Any: ...

    def __getitem__(self, item: COIN) -> Any: ...

    def __setitem__(self, key: COIN, value: int) -> Any: ...

    @property
    def cost(self): ...

    def update(self, char_sheet: dict) -> Any: ...
