from typing import Any, Dict, Union

from item.components import Boolean, Component
from utils.enums import ABILITY


class Requirement(Component, Boolean):
    def __init__(self, requirement: Union[Dict[str, Union[int, ABILITY]], bool], **kwargs: Any) -> None: ...

    @property
    def requirement(self): ...

    @requirement.setter
    def requirement(self, requirement: Any) -> None: ...

    def update(self, char_sheet: dict) -> Any: ...

class AbilityRequirement(Requirement):
    def __init__(self, *, value: int = ..., ability: ABILITY = ...) -> None: ...

    def update(self, char_sheet: dict) -> Any: ...

class Attunement(Requirement):
    def __init__(self, attunement: bool = ...) -> None: ...

    def update(self, char_sheet: dict) -> Any: ...
