from typing import Any, Union

from . import Component as Component


class Mass(int):
    def __init__(self, value: int = ...) -> None: ...

    def __add__(self, other: Any): ...

    def __sub__(self, other: Any): ...

    def to_imperial(self) -> None: ...

    def to_metric(self) -> None: ...


class Pound(Mass):
    def __init__(self, value: int = ...) -> None: ...

    def to_metric(self): ...


class Kilogram(Mass):
    def __init__(self, value: int = ...) -> None: ...

    def to_imperial(self): ...


class Weight(Component):
    def __init__(self, weight: Union[Pound, Kilogram, int] = ...) -> None: ...

    def __add__(self, other: Any): ...

    @property
    def weight(self): ...

    @weight.setter
    def weight(self, value: Any) -> None: ...

    def update(self, char_sheet: dict) -> Any: ...
