from enum import Enum


class BaseEnum(Enum): ...


class WEAPONTYPE(BaseEnum): ...


class SKILL(BaseEnum):
    ACROBATICS: str = ...
    ANIMAL_HANDLING: str = ...
    ARCANA: str = ...
    ATHLETICS: str = ...
    DECEPTION: str = ...
    ENDURANCE: str = ...
    HISTORY: str = ...
    INSIGHT: str = ...
    INTIMIDATION: str = ...
    INVESTIGATION: str = ...
    MEDICINE: str = ...
    NATURE: str = ...
    PERCEPTION: str = ...
    PERFORMANCE: str = ...
    PERSUASION: str = ...
    RELIGION: str = ...
    SLEIGHT_OF_HAND: str = ...
    STEALTH: str = ...
    STREETWISE: str = ...
    SURVIVAL: str = ...


class CONDITION(BaseEnum):
    BLINDED: str = ...
    CHARMED: str = ...
    DEAFENED: str = ...
    FRIGHTENED: str = ...
    GRAPPLED: str = ...
    INCAPACITATED: str = ...
    INVISIBLE: str = ...
    PARALYSED: str = ...
    PETRIFIED: str = ...
    POISONED: str = ...
    PRONE: str = ...
    RESTRAINED: str = ...
    STUNNED: str = ...
    UNCONSCIOUS: str = ...


class RARITY(BaseEnum):
    MUNDANE: str = ...
    COMMON: str = ...
    UNCOMMON: str = ...
    RARE: str = ...
    VERY: str = ...
    LEGENDARY: str = ...

    def describe(self): ...


class DAMAGETYPE(BaseEnum):
    SLASHING: str = ...
    PIERCING: str = ...
    BLUDGEONING: str = ...
    POISON: str = ...
    ACID: str = ...
    FIRE: str = ...
    COLD: str = ...
    RADIANT: str = ...
    NECROTIC: str = ...
    LIGHTNING: str = ...
    THUNDER: str = ...
    FORCE: str = ...
    PSYCHIC: str = ...
    MAGIC: str = ...


class COIN(BaseEnum):
    PLATINUM: str = ...
    GOLD: str = ...
    ELECTRUM: str = ...
    SILVER: str = ...
    COPPER: str = ...


class ABILITY(BaseEnum):
    STR: str = ...
    DEX: str = ...
    CON: str = ...
    WIS: str = ...
    INT: str = ...
    CHA: str = ...


class ARMORTYPE(BaseEnum):
    HEAVY: str = ...
    MEDIUM: str = ...
    LIGHT: str = ...
    NONE: str = ...


class WEAPONPROPERTY(BaseEnum):
    AMMUNITION: str = ...
    FINESSE: str = ...
    HEAVY: str = ...
    LIGHT: str = ...
    LOADING: str = ...
    RANGE: str = ...
    REACH: str = ...
    SPECIAL: str = ...
    THROWN: str = ...
    TWOHANDED: str = ...
    VERSITILE: str = ...
