from typing import Any, Optional

class DiceRoll:
    def __init__(self, expr: str=...) -> None: ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def string(self): ...

def rollv2(dice: DiceRoll) -> Any: ...
def roll(expr: str) -> Any: ...
def roll_standard_table(): ...
def roll_d4(): ...
def roll_d6(): ...
def roll_d8(): ...
def roll_d10(): ...
def roll_d12(): ...
def roll_d20(): ...
def roll_d100(): ...
def roll_d10000(): ...
def roll_4d6_max3(): ...
def roll_4d6_reroll1once_max3(): ...
def roll_3d6(): ...
def roll_for_stats(roll_func: Optional[Any] = ...): ...
